# 1-admin service course router test
GET http://localhost:5010/api/v1/auth/test
###
# 2-admin service add admin
POST http://localhost:5001/api/v1/auth/create/admin
Content-Type: application/json 

{ 
  "name": "test"
}
###
# 3-admin service view all admins
GET http://localhost:5001/api/v1/auth/view/admin
###
# 4-admin service add student
POST http://localhost:5001/api/v1/auth/create/student
Content-Type: application/json 

{ 
  "name": "test",
  "gender": "male",
  "year": 1
}
###
# 3-admin service view all admins
GET http://localhost:5001/api/v1/auth/view/student
###