name: Node.js CI 

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - run: |
        pwd
        cd backend/admin-server
        pm2 stop 0
        pwd
        npm i
        npm run build
        pm2 start 0
        pm2 status
        pm2 save
        cd ..
        pwd
        pm2 status
        sudo service nginx restart