name: Node Continuous Integration

on:
  pull_request:
    branches: [ dev, staging ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: |
          pwd
          cd backend/admin-server
          npm i
          npm test
          npm run build
          cd ..
          cd auth-server
          npm i
          npm run build
          cd ..
          cd course-server
          npm i
          npm run build
          cd ..
          cd result-server
          npm i
          npm run build