name: Staging server

on:
  push:
    branches: [ staging ]
    
jobs:
  build:
    runs-on: [ self-hosted, staging ]
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - run: |
        su - sabbir
        cd /var/www/result-system/_work/buet-hackathon22-devops-team-pixel/buet-hackathon22-devops-team-pixel/backend/admin-server
        docker ps
        docker rm admin-server -f
        docker ps
        docker rmi admin-server -f
        docker build -t admin-server .
        docker run -p 5010:5010 -d --name admin-server admin-server
        docker ps
        pwd