name: Staging server

on:
  push:
    branches: [ staging ]
    
jobs:
  build:
    runs-on: [ self-hosted, staging ]
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: 16.x
    - run: |
        cd backend/admin-server
        pwd